### ISSUE TITLE
Have you considered compe ?

### ISSUE THREAD

**Issue by thecontinium** [rafi/vim-config#185]
Requires neovim nightly but I’m thinking of moving to this. 
https://github.com/hrsh7th/nvim-compe

cheers

**Comment by rafi** [comment]
Hi @thecontinium, thanks for recommending compe. I've been testing it the last 2 days with nvim-lspconfig and the whole experience is much better, seamless. This will mean that I'll have to diverge configuration, to keep supporting Vim.

This is what I'm trying out: (Removed: all `asyncomplete` sources, `vim-lsp`, and `vim-lsp-settings`)

```yaml
- { repo: kabouzeid/nvim-lspinstall, lazy: true }
- { repo: ray-x/lsp_signature.nvim, lazy: true }

- repo: neovim/nvim-lspconfig
  depends: [ nvim-lspinstall, lsp_signature.nvim ]
  on_event: VimEnter
  hook_post_source: luafile $VIM_PATH/config/plugins/lspconfig.lua

- repo: hrsh7th/nvim-compe
  if: has('nvim-0.5')
  on_event: InsertEnter
  # depends: compe-tmux
  hook_post_source: luafile $VIM_PATH/config/plugins/compe.lua
  hook_source: |-
    augroup user_plugin_compe
      autocmd!
      autocmd FileType denite-filter,clap_input
        \ call compe#setup({'enabled': v:false}, 0)
    augroup END

#- { repo: andersevenrud/compe-tmux, lazy: true }

- repo: hrsh7th/vim-vsnip
  depends: [ vim-vsnip-integ, friendly-snippets ]
  on_event: InsertEnter
  hook_post_source: |-
    let g:vsnip_filetypes = {}
    let g:vsnip_filetypes.javascriptreact = ['javascript']
    let g:vsnip_filetypes.typescriptreact = ['typescript']

- { repo: hrsh7th/vim-vsnip-integ, lazy: true }
- { repo: rafamadriz/friendly-snippets, lazy: true, merged: 0 }
```

`$VIM_PATH/config/plugins/compe.lua`
```lua
-- Nvim Compe
--

require'compe'.setup({
  enabled = true,
  source = {
    path = true,
    buffer = true,
    spell = true,
    nvim_lsp = true,
    vsnip = true,
    -- tmux = true,
  },
})

local t = function(str)
  return vim.api.nvim_replace_termcodes(str, true, true, true)
end

local check_back_space = function()
  local col = vim.fn.col('.') - 1
  if col == 0 or vim.fn.getline('.'):sub(col, col):match('%s') then
    return true
  else
    return false
  end
end

_G.confirm_completion = function()
  if vim.fn.pumvisible() == 0 then
    return t '<Plug>delimitMateCR'
  elseif vim.fn.complete_info()['selected'] ~= -1 then
    return vim.fn['compe#confirm']({ keys = t '<Plug>delimitMateCR', mode = '' })
  else
    return t '<C-e><Plug>delimitMateCR'
  end
end

-- Use (s-)tab to:
--- move to prev/next item in completion menuone
--- jump to prev/next snippet's placeholder
_G.tab_complete = function()
  if vim.fn.pumvisible() == 1 then
    return t "<C-n>"
  elseif vim.fn.call("vsnip#available", {1}) == 1 then
    return t "<Plug>(vsnip-expand-or-jump)"
  elseif check_back_space() then
    return t "<Tab>"
  else
    return vim.fn['compe#complete']()
  end
end
_G.s_tab_complete = function()
  if vim.fn.pumvisible() == 1 then
    return t "<C-p>"
  elseif vim.fn.call("vsnip#jumpable", {-1}) == 1 then
    return t "<Plug>(vsnip-jump-prev)"
  else
    return t "<S-Tab>"
  end
end

-- require'lsp_signature'.on_attach()

vim.api.nvim_set_keymap("i", "<Tab>", "v:lua.tab_complete()", {expr = true})
vim.api.nvim_set_keymap("s", "<Tab>", "v:lua.tab_complete()", {expr = true})
vim.api.nvim_set_keymap("i", "<S-Tab>", "v:lua.s_tab_complete()", {expr = true})
vim.api.nvim_set_keymap("s", "<S-Tab>", "v:lua.s_tab_complete()", {expr = true})

vim.api.nvim_set_keymap("i", "<CR>", "v:lua.confirm_completion()", {expr = true})

local args = {expr = true, noremap = true, silent = true}
vim.api.nvim_set_keymap("i", "<C-e>", "compe#close('<C-e>')", args)
vim.api.nvim_set_keymap("i", "<C-u>", "compe#scroll({'delta': 4})", args)
vim.api.nvim_set_keymap("i", "<C-d>", "compe#scroll({'delta': -4})", args)
```

`$VIM_PATH/config/plugins/lspconfig.lua`
```lua
-- nvim-lspconfig
--

local on_attach = function(client, bufnr)
  local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
  local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end

  -- Mappings.
  local opts = { noremap=true, silent=true }
  buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
  buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
  buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
  buf_set_keymap('n', 'gy', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
  buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
  buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
  buf_set_keymap('n', ',s', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
  buf_set_keymap('n', ',wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
  buf_set_keymap('n', ',wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
  buf_set_keymap('n', ',wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
  buf_set_keymap('n', ',rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
  buf_set_keymap('n', '<Leader>ca', '<cmd>lua vim.lsp.buf.code_action()<CR>', opts)
  buf_set_keymap('n', '<Leader>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
  buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
  buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
  buf_set_keymap('n', '<Leader>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)

  -- Set some keybinds conditional on server capabilities
  if client.resolved_capabilities.document_formatting then
    buf_set_keymap("n", ",f", "<cmd>lua vim.lsp.buf.formatting()<CR>", opts)
  end
  if client.resolved_capabilities.document_range_formatting then
    buf_set_keymap("v", ",f", "<cmd>lua vim.lsp.buf.range_formatting()<CR>", opts)
  end

  -- Set autocommands conditional on server_capabilities
  if client.resolved_capabilities.document_highlight then
    vim.api.nvim_exec([[
      hi! LspReferenceRead ctermbg=237 guibg=#373b41
      hi! LspReferenceText ctermbg=237 guibg=#373b41
      hi! LspReferenceWrite ctermbg=237 guibg=#373b41
      augroup lsp_document_highlight
        autocmd! * <buffer>
        autocmd CursorHold <buffer> lua vim.lsp.buf.document_highlight()
        autocmd CursorMoved <buffer> lua vim.lsp.buf.clear_references()
      augroup END
    ]], false)
  end

  -- buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')
  require "lsp_signature".on_attach({
    bind = true,
    hint_enable = false,
    handler_opts = { border = "single" },
    decorator = {"**", "**"},
  })
end

local function setup_servers()
  require'lspinstall'.setup()
  local servers = require'lspinstall'.installed_servers()
  for _, server in pairs(servers) do
    require'lspconfig'[server].setup { on_attach = on_attach }
  end
end

setup_servers()

-- Automatically reload after `:LspInstall <server>` so we don't have to restart neovim
require'lspinstall'.post_install_hook = function ()
  setup_servers() -- reload installed servers
  vim.cmd("bufdo e") -- this triggers the FileType autocmd that starts the server
end
```

**Comment by thecontinium** [comment]
Hi 

I've personally not used vim for a couple of years now so ....
I am using another Lua plugin for clojure. The speed of these plugins gives a much more seamless integration.
I'm going to try your config and I'll let you know.
cheers

**Comment by mn-dimension** [comment]
hi - any reason you commented out tmux ?

**Comment by thecontinium** [comment]
I have made a few minor tweaks to the setup for lsp which you can see [here](https://github.com/thecontinium/vim-config/blob/master/config/local.plugins/lspconfig.lua ) 

``` yaml
- repo: neovim/nvim-lspconfig
  depends: [ nvim-lspinstall, lsp_signature.nvim ]
  on_event: VimEnter
  hook_post_source: luafile $VIM_PATH/config/local.plugins/lspconfig.lua
  hook_add: |
    sign define LspDiagnosticsSignError text=✖ texthl=LspDiagnosticsSignError linehl= numhl=
    sign define LspDiagnosticsSignWarning text=⬪ texthl=LspDiagnosticsSignWarning linehl= numhl=
    sign define LspDiagnosticsSignInformation text=▫ texthl=LspDiagnosticsSignInformation linehl= numhl=
    sign define LspDiagnosticsSignHint text=▪ texthl=LspDiagnosticsSignHint linehl= numhl=
```

I'm sticking with this rather than asyncomplete; Lua integration is a game changer.
