### ISSUE TITLE
Proposed Changes to nvim branch

### ISSUE THREAD

**Issue by thecontinium** [rafi/vim-config#195]
Hi 

I have created an nvim branch with some proposed changes around

- fern : use telescope for gf,gr

``` viml
lua << EOF
function _G.fernfind(search_dirs)
  require'telescope.builtin'.find_files({search_dirs = search_dirs, theme=get_dropdown, previewer=false})
end
EOF
function! s:find(helper) abort
	let l:paths = s:get_selected_paths(a:helper)
	silent execute 'wincmd w'
	call  v:lua.fernfind(l:paths)
endfunction

lua << EOF
function _G.ferngrep(search_dirs)
  require'telescope.builtin'.grep_string({search = vim.fn.input("Grep:"), search_dirs = search_dirs})
end
EOF
function! s:grep(helper) abort
	let l:paths = s:get_selected_paths(a:helper)
	silent execute 'wincmd w'
	call  v:lua.ferngrep(l:paths)
endfunction
```

- telescope; setup zoxide and telescope builtin files grep_string used by fern; load when any telescope lua module is used

``` yaml
- repo: nvim-telescope/telescope.nvim
  if: has("nvim-0.5")
  depends: [ todo-comments.nvim, session-lens, telescope-zoxide]
  on_lua: 'telescope'
  hook_post_source: lua require('plugins.telescope')

- { repo: rmagatti/session-lens, if: has("nvim-0.5"), lazy: true }
- { repo: jvgrootveld/telescope-zoxide, if: has("nvim-0.5"), lazy: true }
```

``` lua
		find_command = {'rg', '--no-heading', '--with-filename', '--line-number', '--column', '--smart-case'},
		vimgrep_arguments = { 'rg', '--color=never', '--no-heading', '--with-filename', '--line-number', '--column', '--smart-case'},

		-- layout_strategy = 'flex',
		winblend = 7,
```

``` lua
telescope.load_extension('session-lens')
telescope.load_extension('zoxide')
```

**Comment by rafi** [comment]
checkout the new revisions in the `nvim` branch

**Comment by thecontinium** [comment]
You've been busy :) Thanks.

Have you had a chance to make the Telescope setup compatible with the latest setup changes ?

**Comment by thecontinium** [comment]
If you open fern and gr before using Telescope it is not loaded and a dente error is given. 
Adding on_cmd as below fixes it.

``` yaml
- repo: nvim-telescope/telescope.nvim
  if: has("nvim-0.5")
  depends: [ todo-comments.nvim, session-lens, telescope-zoxide]
  on_lua: 'telescope'
  on_cmd: 'Telescope'
  hook_post_source: lua require('plugins.telescope')

```
