### ISSUE TITLE
nvim branch: adding dap plugins (lua plugins)

### ISSUE THREAD

**Issue by kraxli** [rafi/vim-config#198]
I am struggling with the load process of **lua plugins** in combination with `dein`. I have tried many things to add **dap** (Debug Adapter Protocol) plugins.

Everything is loaded and working correctly after calling `dein#recache_runtimepath()` but without recaching, the plugins are not loaded including the files in `lua/plugins`.

My latest attempt to include these dap-plugins:

file `config/local.plugins.yaml`:

```yaml
- repo: nvim-telescope/telescope-dap.nvim
  if: has('nvim-0.5')
  lazy: true

- repo: mfussenegger/nvim-dap
  if: has('nvim-0.5')
  depends: [ auto-session, telescope.nvim, nvim-dap-python, nvim-dap-ui ]
  hook_post_source: lua require('plugins.dap')

- repo: mfussenegger/nvim-dap-python
  if: has('nvim-0.5')
  hook_post_source: lua require('plugins.dap-python')

- repo: rcarriga/nvim-dap-ui
  if: has('nvim-0.5')
  hook_post_source: lua require('plugins.dap-ui')
```

To the dependency in `config/plugins.yaml` for `telescope.nvim` I have added:

```yaml
- repo: nvim-telescope/telescope.nvim
  if: has("nvim-0.5")
  depends: [ todo-comments.nvim, session-lens, telescope-dap.nvim ]
  on_cmd: Telescope
  hook_post_source: lua require('plugins.telescope')
```

At the end of `lua/plugins/telescope.lua` I added:

```lua
-- Telescope extensions
...
telescope.load_extension('dap')
```

What am I doing wrong? Can anybody help me out on this such that the plugins are loaded also without recaching?

My environment:

Branch: nvim
Neovim: version 0.5
System: Linux Mint 20 Ulyana
Terminal: GNOME Terminal 3.36.2

Many thanks!

**Comment by rafi** [comment]
@kraxli for the dap part plugins, try

```yaml
- repo: nvim-telescope/telescope-dap.nvim
  if: has('nvim-0.5')
  lazy: true

- repo: mfussenegger/nvim-dap
  if: has('nvim-0.5')
  depends: [ auto-session ]
  on_lua: dap
  hook_post_source: lua require('plugins.dap')

- repo: mfussenegger/nvim-dap-python
  if: has('nvim-0.5')
  depends: mfussenegger/nvim-dap
  on_lua: dap-python
  hook_post_source: lua require('plugins.dap-python')

- repo: rcarriga/nvim-dap-ui
  if: has('nvim-0.5')
  depends: mfussenegger/nvim-dap
  on_lua: dapui
  hook_post_source: lua require('plugins.dap-ui')
```
