### ISSUE TITLE
Whichkey does not work with lazy loading

### ISSUE THREAD

**Issue by tobias2912** [rafi/vim-config#229]
I get no popups from Whichkey when starting nvim, but running :WhichKey works. Removing ```on_cmd: WhichKey```  from ```config/plugins.yaml``` makes it work on startup on my machine, is this intended behavior?

**Comment by rafi** [comment]
Yes, this is the intended behavior, because I don't need these hints by default.
You can override with your own `config/plugins.local.yaml` like this:
```yaml
- repo: folke/which-key.nvim
  if: has('nvim-0.5')
  on_event: VimEnter
  hook_post_source: lua require('plugins.which-key')
```

This will load the plugin immediately when you enter Neovim.
